import { DELIVERY_STATUSES, DELIVERY_TRANSITIONS } from '@/constants/deliveryStatus';

export const DELIVERY_CONSTANTS = {
  STATUSES: DELIVERY_STATUSES,
  TRANSITIONS: DELIVERY_TRANSITIONS,
  BASE_FEE: 1000
};