export const DELIVERY_STATUSES = {
  PENDING: 'pending',
  ASSIGNED: 'assigned',
  PICKED_UP: 'picked_up',
  ON_THE_WAY: 'on_the_way',
  ARRIVED: 'arrived_at_customer',
  DELIVERED: 'delivered',
  CANCELLED: 'cancelled'
};

export const DELIVERY_TRANSITIONS = {
  [DELIVERY_STATUSES.PENDING]: [DELIVERY_STATUSES.ASSIGNED, DELIVERY_STATUSES.CANCELLED],
  [DELIVERY_STATUSES.ASSIGNED]: [DELIVERY_STATUSES.PICKED_UP, DELIVERY_STATUSES.CANCELLED],
  [DELIVERY_STATUSES.PICKED_UP]: [DELIVERY_STATUSES.ON_THE_WAY, DELIVERY_STATUSES.CANCELLED],
  [DELIVERY_STATUSES.ON_THE_WAY]: [DELIVERY_STATUSES.ARRIVED, DELIVERY_STATUSES.CANCELLED],
  [DELIVERY_STATUSES.ARRIVED]: [DELIVERY_STATUSES.DELIVERED, DELIVERY_STATUSES.CANCELLED],
  [DELIVERY_STATUSES.DELIVERED]: [],
  [DELIVERY_STATUSES.CANCELLED]: []
};